version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: server-node
    ports:
      - "5000:5000"
    depends_on:
      - "mongo"
    environment:
      MONGODB_URL: mongodb://mongo:27017/jwt
      DB_NAME: my_db
  mongo:
    container_name: db_container
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - /data/db/mongo